name: learn2recycle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  flutter_google_maps_webservices: ^1.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_vision: ^1.1.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/recycle.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/recycle.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/labels.txt
    - assets/best_saved_model.tflite

  fonts:
    - family: OleoScript
      fonts:
        - asset: assets/fonts/OleoScript-Regular.ttf
        - asset: assets/fonts/OleoScript-Bold.ttf
          weight: 700

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
